#!/usr/bin/lua

local site = require 'gluon.site_config'
local users = require 'gluon.users'
local util = require 'gluon.util'
local fs = require 'nixio.fs'

local uci = require('simple-uci').cursor()


uci:section('network', 'interface', 'mesh_vpn', {
	ifname = 'mesh-vpn',
	proto = 'gluon_mesh',
	transitive = true,
	fixed_mtu = true,
	macaddr = util.generate_mac(7),
	mtu = site.mesh_vpn.mtu,
})

uci:save('network')


if fs.access('/etc/config/gluon-simple-tc') then
	os.rename('/etc/config/gluon-simple-tc', '/etc/config/simple-tc')
end

if not uci:get('simple-tc', 'mesh_vpn') then
	local config = {
		ifname = 'mesh-vpn',
		enabled = false,
	}


	if site.mesh_vpn.bandwidth_limit then
		if site.mesh_vpn.bandwidth_limit.enabled then
			config.enabled = true
		end

		config.limit_ingress = site.mesh_vpn.bandwidth_limit.ingress
		config.limit_egress = site.mesh_vpn.bandwidth_limit.egress
	end

	uci:section('simple-tc', 'interface', 'mesh_vpn', config)
	uci:save('simple-tc')
end


-- The previously used user and group are removed, we now have a generic group
users.remove_user('gluon-fastd')
users.remove_group('gluon-fastd')

users.add_group('gluon-mesh-vpn', 800)

uci:section('firewall', 'include', 'mesh_vpn_dns', {
	type = 'restore',
	path = '/lib/gluon/mesh-vpn/iptables.rules',
	family = 'ipv4',
})

uci:save('firewall')


-- VPN migration
local has_fastd = fs.access('/lib/gluon/mesh-vpn/fastd')
local fastd_enabled = uci:get('fastd', 'mesh_vpn', 'enabled')

local has_tunneldigger = fs.access('/lib/gluon/mesh-vpn/tunneldigger')
local tunneldigger_enabled = uci:get('tunneldigger', 'mesh_vpn', 'enabled')

-- if fastd is installed
if has_fastd then
	-- if fastd_enabled is not set (first install with fastd)
	if fastd_enabled == nil then
		-- if tunneldigger_enabled is also not set (first install generally)
		if tunneldigger_enabled == nil then
			-- set fastd.mesh_vpn.enabled from site config
			uci:set('fastd', 'mesh_vpn', 'enabled', site.mesh_vpn.enabled or false)
		-- if tunneldigger is installed and configured
		elseif has_tunneldigger then
			-- disable fastd
			uci:set('fastd', 'mesh_vpn', 'enabled', false)
		-- tunneldigger is not installed but was installed previously
		else
			-- tunneldigger_enabled (old) -> fastd_enabled
			uci:set('fastd', 'mesh_vpn', 'enabled', tunneldigger_enabled == '1')
		end
	-- if fastd is off, tunneldigger ist not installed but was installed previously
	elseif fastd_enabled == '0' and not has_tunneldigger and not tunneldigger_enabled == nil then
		-- tunneldigger_enabled (old) -> fastd_enabled
		uci:set('fastd', 'mesh_vpn', 'enabled', tunneldigger_enabled == '1')
	-- else: do nothing
	end
else
	uci:delete('fastd', 'mesh_vpn')
end

-- if tunneldigger is installed
if has_tunneldigger then
	-- if tunneldigger_enabled is not set (first install with tunneldigger)
	if tunneldigger_enabled == nil then
		-- if fastd is installed
		if has_fastd then
			-- disable tunneldigger
			uci:set('tunneldigger', 'mesh_vpn', 'enabled', false)
		-- fastd is not installed
		else
			-- if fastd_enabled ist also not set (first install generally)
			if fastd_enabled == nil then
				-- set tunneldigger.mesh_vpn.enabled from site config
				uci:set('tunneldigger', 'mesh_vpn', 'enabled', site.mesh_vpn.enabled or false)
			-- fast is not installed but was installed previously
			else
				-- fastd_enabled (old) -> tunneldigger_enabled
				uci:set('tunneldigger', 'mesh_vpn', 'enabled', fastd_enabled == '1')
			end
		end
	-- if fastd is installed and enabled
	elseif has_fastd and fastd_enabled == '1' then
		-- disable tunneldigger
		uci:set('tunneldigger', 'mesh_vpn', 'enabled', false)
	-- else: do nothing
	end
else
	uci:delete('tunneldigger', 'mesh_vpn')
end

uci:save('fastd')
uci:save('tunneldigger')
